#!/bin/bash

# Script for updating data.  After pulling and merging, it will
# regenerate the history & update the notebooks.

# First, pull and merge latest data first, as in:
#    git fetch --all -p
#    git merge CSSEGISandData/master 

# Then run this script

# Generate history.csv file:
python Scripts/generate-history.py

# Update Analysis:

jupyter nbconvert --to notebook --inplace --execute Notebooks/Analysis.ipynb
